package com.SCGEOrientaIA.algorithms;

public enum EnumSubject {
	ASSUNTONAODEFINIDO("ASSUNTO NÃO DEFINIDO", 1),
	CAPACITACAOTREINAMENTO("CAPACITAÇÃO/ TREINAMENTO", 2),
	CLASSIFICACAODADESPESA ("CLASSIFICAÇÃO DA DESPESA", 3),
	CONTRATOLICITACAO("CONTRATO E LICITAÇÃO", 4),
	CONTROLEINTERNO("CONTROLE INTERNO", 5),
	CONVENIO("CONVÊNIO", 6),
	DESPESAEXERCICIOSANTERIORES("DESPESA DE EXERCÍCIOS ANTERIORES", 7),
	DESPESAPESSOAL("DESPESA DE PESSOAL", 8),
	DIARIA("DIÁRIA", 9),
	DIVERSOS("DIVERSOS", 10),
	DOCUMENTOFISCALCOMPROVACAODESPESA("DOCUMENTO FISCAL/COMPROVAÇÃO DE DESPESA", 11),
	EMPRENHOLIQUIDACAOPAGAMENTOS("EMPENHOS/ LIQUIDAÇÃO/ PAGAMENTO", 12),
	PCGPMG("PCG / PMG", 13),
	PRESTACAODECONTAS("PRESTAÇÃO DE CONTAS", 14),
	REFERENCIALEGALNORMALEGAL("REFERÊNCIA LEGAL/NORMA LEGAL", 15),
	RESTOSAPAGAR("RESTOS A PAGAR", 16),
	RETENCOES("RETENÇÕES", 17),
	SEMTRATAMENTO("SEM TRATAMENTO", 18),
	SUPRIMENTOINDIVIDUAL("SUPRIMENTO INDIVIDUAL", 19),
	SUPRIMENTOINSTITUCIONAL("SUPRIMENTO INSTITUCIONAL", 20);
	
	private String subject;
	private Integer id;
	
	EnumSubject(String s, Integer i){
		this.setSubject(s);
		this.setId(i);
	}

	public String getSubject() {
		return subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
}
